[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]
dependsOn = ["install"]

[start]
cmd = "npm start"

[variables]
SKIP_ENV_VALIDATION = "1"
NODE_ENV = "production"
