export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
  textOperators: [
    { label: "يحتوي على", value: "iLike" as const },
    { label: "لا يحتوي على", value: "notILike" as const },
    { label: "يساوي", value: "eq" as const },
    { label: "لا يساوي", value: "ne" as const },
    { label: "فارغ", value: "isEmpty" as const },
    { label: "غير فارغ", value: "isNotEmpty" as const },
  ],
  numericOperators: [
    { label: "يساوي", value: "eq" as const },
    { label: "لا يساوي", value: "ne" as const },
    { label: "أصغر من", value: "lt" as const },
    { label: "أصغر من أو يساوي", value: "lte" as const },
    { label: "أكبر من", value: "gt" as const },
    { label: "أكبر من أو يساوي", value: "gte" as const },
    { label: "بين", value: "isBetween" as const },
    { label: "فارغ", value: "isEmpty" as const },
    { label: "غير فارغ", value: "isNotEmpty" as const },
  ],
  dateOperators: [
    { label: "يساوي", value: "eq" as const },
    { label: "لا يساوي", value: "ne" as const },
    { label: "قبل", value: "lt" as const },
    { label: "بعد", value: "gt" as const },
    { label: "في أو قبل", value: "lte" as const },
    { label: "في أو بعد", value: "gte" as const },
    { label: "بين", value: "isBetween" as const },
    // { label: "نسبة إلى اليوم", value: "isRelativeToToday" as const },
    { label: "فارغ", value: "isEmpty" as const },
    { label: "غير فارغ", value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: "يساوي", value: "eq" as const },
    { label: "لا يساوي", value: "ne" as const },
    { label: "فارغ", value: "isEmpty" as const },
    { label: "غير فارغ", value: "isNotEmpty" as const },
  ],
  multiSelectOperators: [
    { label: "يحتوي على أي من", value: "inArray" as const },
    { label: "لا يحتوي على أي من", value: "notInArray" as const },
    { label: "فارغ", value: "isEmpty" as const },
    { label: "غير فارغ", value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: "يساوي", value: "eq" as const },
    { label: "لا يساوي", value: "ne" as const },
  ],
  sortOrders: [
    { label: "تصاعدي", value: "asc" as const },
    { label: "تنازلي", value: "desc" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    // "isRelativeToToday",
  ] as const,
  joinOperators: [
    { label: "و", value: "and" },
    { value: "or", label: "او" },
  ] as const,
};
